# Application Configuration
server:
  port: 8093

# ===============================
# DB - MySQL Configuration
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/invoicedb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  # ===============================
  # JPA / Hibernate
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8094/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"      